services:
  008_frankenphp_workermode:
    build:
      context: ../../
      dockerfile: "./runtimes/008_frankenphp_workermode/frankenphp/frankenphp.Dockerfile"
    image: "008_frankenphp_workermode"
    container_name: "008_frankenphp_workermode"
    hostname: symfony7site
    networks:
      - php-benchmarks
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
