services:
  004_nginx_unit:
    build:
      context: ../../
      dockerfile: "./runtimes/004_nginx_unit/unit/unit.Dockerfile"
    image: 004_nginx_unit
    container_name: "004_nginx_unit"
    hostname: symfony7site
    ports:
      - '80:80'
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
