services:
  006_nginx:
    build:
      context: ../../
      dockerfile: "./runtimes/006_nginx_roadrunner/nginx/nginx.Dockerfile"
    image: 006_nginx
    container_name: "006_nginx"
    hostname: symfony7site
    ports:
      - '80:80'
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'

  006_roadrunner:
    build:
      context: ../../
      dockerfile: "./runtimes/006_nginx_roadrunner/roadrunner/roadrunner.Dockerfile"
    image: "006_roadrunner"
    container_name: "006_roadrunner"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
