services:
  001_apache_modphp:
    build:
      context: ../../
      dockerfile: ./runtimes/001_apache_modphp/apache.Dockerfile
    image: 001_apache_modphp
    container_name: 001_apache_modphp
    hostname: symfony7site
    ports:
      - "80:80"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
