services:
  005_roadrunner:
    build:
      context: ../../
      dockerfile: "./runtimes/005_roadrunner/roadrunner/roadrunner.Dockerfile"
    image: "005_roadrunner"
    container_name: "005_roadrunner"
    hostname: symfony7site
    ports:
      - '80:80'
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
