services:
  007_frankenphp:
    build:
      context: ../../
      dockerfile: "./runtimes/007_frankenphp/frankenphp/frankenphp.Dockerfile"
    image: "007_frankenphp"
    container_name: "007_frankenphp"
    hostname: symfony7site
    networks:
      - php-benchmarks
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
