services:
  010_adapterman:
    build:
      context: ../../
      dockerfile: "./runtimes/010_adapterman/adapterman/adapterman.Dockerfile"
    image: "010_adapterman"
    container_name: "010_adapterman"
    hostname: symfony7site
    ports:
      - '8000:80'
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'
        reservations:
          cpus: '${CPU:-1}'
          memory: '${MEM:-1}gb'

networks:
  php-benchmarks:
    external: true
    name: php-benchmarks
